import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Radical Sensitive Leadership",
  description: "Generated by Dr. Miriam von Felbert",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

        {/* 👇 GHOST PORTAL SCRIPT */}
        <script
        defer
        src="https://ghost.radicalsensitiveleadership.com/portal.min.js"
        data-ghost="https://ghost.radicalsensitiveleadership.com/"
        data-key="pub_0d94e22b89520e251f032d0c65"
        data-api="v3"
        crossOrigin="anonymous"
      />
      </body>
    </html>
  );
}

